Cleanup nautilus listeners
This has been an issue with dash-to-panel for quite some time now.
Whenever you would start nautilus you would see:

TypeError: dockManager is null getRunningApps@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:653:9
  wrapWindowsManagerApp/fileManagerApp._updateWindows@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:258:9
  wrapWindowsManagerApp/windowsChangedId<@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:250:24

However this file belongs to dash-to-dock and not dash-to-panel.

So I did some digging. Turns out that the changes introduced in commit 53f85cf
did not cleanup the listeners. Now when dash-to-panel is started and dash-to-dock
has destroyed itself, these now obsolete listeners will try to access dockManager
when nautilus is opened and fail.
Thereby also preventing dash-to-panel from getting notified about the changed window.